services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatMiniProgramDeliveryReturnBundle\Command\:
    resource: '../../Command/'
  WechatMiniProgramDeliveryReturnBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatMiniProgramDeliveryReturnBundle\Repository\:
    resource: '../../Repository/'
  WechatMiniProgramDeliveryReturnBundle\Service\:
    resource: '../../Service/'
